site_name: Documentação | Bruno Dórea
site_author: Bruno Dórea
site_url: https://www.brunodorea.com.br/

theme: 
  name: dracula
  favicon: https://github.com/BH-Tec.png
  logo: https://github.com/BrunoDorea.png

nav:
  - Home: index.md
  - Projetos:
    - Chatbot: nav/chatbot.md
    - Analise de dados Empresarial: nav/analise-dados-emp.md
    - Analise de dados para Business Intelligence: nav/analise-dados-bi.md
  - Sobre: about.md

